### ISSUE TITLE
コラムページデザイン

### ISSUE THREAD

**Issue by teiflower** [sota-ma/soma#91]
article detailページと同質のデザイン・レイアウトにする

**Comment by teiflower** [comment]
h4とかそういうのだけはいじれるって聞いてたけどむしろ本文のデザインん変更する方法なくない？
@kkiriyama

**Comment by kkiriyama** [comment]
```css
h2 {
	margin: 10px;
}
```
とかでダメでした？
